<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permohonan_model extends CI_Model
{

    public $table = 'tbl_permohonan';
    public $id = 'id_permohonan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_permohonan,tanggal,nama_usaha,alamat,nama_owner,logo,surat,ttd,id_user,status');
        $this->datatables->from('tbl_permohonan');            
        $this->datatables->where('id_user', $_SESSION['id_users']);
        //add this line for join
        //$this->datatables->join('table2', 'tbl_permohonan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('permohonan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('permohonan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('permohonan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_permohonan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        // $this->db->where($this->id_user, $this->session->userdata('id_users'));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_permohonan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nama_usaha', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_owner', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('surat', $q);
	$this->db->or_like('ttd', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_permohonan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nama_usaha', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_owner', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('surat', $q);
	$this->db->or_like('ttd', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Permohonan_model.php */
/* Location: ./application/models/Permohonan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-11-27 14:16:19 */
/* http://harviacode.com */